### ISSUE TITLE
Stuck at step 3

### ISSUE THREAD

**Issue by MIBmusic** [markdumay/synology-docker#19]
Probably I am missing something but the script is stuck at step 3. I can see Docker has stopped but the containers are still running. Is that even possible? Or should I let docker run and shut the containers?

**Comment by markdumay** [comment]
That’s strange indeed. The script should stop the Docker service including all running containers. Can you share the script command and your console output?

**Comment by MIBmusic** [comment]
Hi Mark, I run Home Assistant as a container and I found out that the Supervisor and HA start again within a minute after they stopped. I think I need to figure out how that happens with that before I try again. I will let you know ok?

**Comment by MIBmusic** [comment]
ash-4.3# cd synology-docker
ash-4.3# sh syno_docker_update.sh update
Update Docker Engine and Docker Compose on Synology to target version

Current DSM version: 6.2.3
Current Docker version: 18.09.8
Current Docker Compose version: 1.24.0
Target Docker version: 19.03.12
Target Docker Compose version: 1.26.2

WARNING! This will replace:
  - Docker Engine
  - Docker Compose
  - Docker daemon log driver

Are you sure you want to continue? [y/N] y
Step 1 from 9: Downloading target Docker binary (https://download.docker.com/lin                                       ux/static/stable/x86_64/docker-19.03.12.tgz)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 57.9M  100 57.9M    0     0  56.7M      0  0:00:01  0:00:01 --:--:-- 56.7M
Step 2 from 9: Downloading target Docker Compose binary (https://github.com/dock                                       er/compose/releases/download/1.26.2/docker-compose-Linux-x86_64)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   638  100   638    0     0   5714      0 --:--:-- --:--:-- --:--:--  5747
100 11.6M  100 11.6M    0     0  1134k      0  0:00:10  0:00:10 --:--:-- 1502k
Step 3 from 9: Stopping Docker service

**Comment by markdumay** [comment]
The version checks and the first two steps appear to be fine. Normally, step 3 would then either return a confirmation it stopped synoservice successfully, or return an error message. It seems no message is returned at all? What happens if you run 'synoservicectl --status pkgctl-Docker' directly from your command line?

**Comment by MIBmusic** [comment]
Hi Mark,

So I was at the point that Docker stopped, the containers where still running and the script was stuck at step 3. At that time I started docker again and at some point during the startup your script began to run and finished the update. I have no idea what happened and how that is possible but it did happen!

**Comment by markdumay** [comment]
Very strange! The only thing I can imagine is that synoservicectl has entered a race condition (deadlock) with the Home Assistant containers preventing a proper shutdown of the Docker service. I might need to add a timeout for the update script to prevent endless waiting for synoservicectl. Did the update work correctly in the end though?

**Comment by MIBmusic** [comment]
Could this be happening in combination with the very persistant Home Assistant?

https://docs.docker.com/config/containers/live-restore/

By the way, I am good and the update went prefectly so thanks for that!!!

**Comment by markdumay** [comment]
Glad to hear it worked in the end! It’s worth looking into live restore indeed, it could well be the cause. I haven’t seen it before. In any case, I’ll create a new issue to add the timeout functionality to the script.
