### ISSUE TITLE
Compose version Unknown + Minor Typo

### ISSUE THREAD

**Issue by hirenshah** [markdumay/synology-docker#2]
```
Current DSM version: 6.2.3
Current Docker version: 18.09.8
Current Docker Compose version: 1.24.0
Target Docker version: 19.03.11
Target Docker Compose version: Unknown
Step 1 from 6: Stopping Docker service
pkgctl-Docker stoped.
```

Should there be a Docker Compose version displayed, rather than "Unknown"?

Also, "stopped" is spelt incorrectly :p

**Comment by markdumay** [comment]
Strange, the script should indeed detect the latest compose version automatically. Can you try running below command from your Synology command line? It should return '1.26.0'.

```
curl -s "https://github.com/docker/compose/tags" | egrep "a href=\"/docker/compose/releases/tag/[0-9]+.[0-9]+.[0-9]+\"" | head -1 | cut -c 45- | sed "s/\">//g"
```

The message `pkgctl-Docker stoped.` is generated by `synoservicectl`, so unfortunately not a message I can change myself.

**Comment by hirenshah** [comment]
Yep, it returned:
`1.26.0`

Haha, that makes the typo even funnier :D

**Comment by markdumay** [comment]
My guess is that the web scraping call sometimes times out, perhaps GitHub has some kind of rate limiting in place. I encountered a similar issue in another repository. My suggestion is to include a default value for the Docker engine and Docker Compose binary to revert back to in case curl fails.
