### ISSUE TITLE
Portainer container doesn't run

### ISSUE THREAD

**Issue by siddjellali** [markdumay/synology-docker#28]
Hi, after an upgrade with the script I cannot start any of my container.
I have this error message : "COI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"bin/bash"...

Current DSM version: 6.2.3
Current Docker version: 19.03.8
Current Docker Compose version: 1.27.4

My Synology is a DS918+

**Comment by markdumay** [comment]
That's unfortunate. I haven't encountered this error before. Are you able start any new containers? For example, does `docker run hello-world` work?

**Comment by siddjellali** [comment]
Yes ! Works well !
When i try to run portainer.

`docker run -d -p 8000:8000 -p 9000:9000 --name=portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v /volume1/docker/portainer:/data portainer/portainer-ce`

and i try to run the bash command in CLi: 

```
# docker exec -it portainer /bin/bash
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown```

**Comment by markdumay** [comment]
Have you tried `docker exec -it portainer /bin/sh`? I'm not sure if `bash` is present in the portainer image.

**Comment by siddjellali** [comment]
Yes it's the same !

```
# docker exec -it portainer /bin/sh
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory": unknown
```

If i restore my backup, Portainer runs well (expect for the environment bug i try to correct with your script)

**Comment by siddjellali** [comment]
For information, 

I delete all my container  and install portainer-ce with my directory conf --> same error
I delete all my container  and install portainer-ce without my directory conf --> same error
I delete all my container  and install portainer-agent --> same error
I try to install sonarr (https://hub.docker.com/r/linuxserver/sonarr) and it works well...

Can you try portainer-ce in your synology ?

**Comment by markdumay** [comment]
I did a quick Google search, and found this [issue](https://github.com/portainer/portainer/issues/1454):

> Portainer is based off “scratch” so we have no bash in the container, which means you cannot console or exec into the container.

It looks like neither `bash` or `sh` is part of the portainer image. I did a test on my mac with Docker CE, and I get a similar error. However, the portainer website can be reached at `localhost:9000`. From your NAS console, try:
```
curl -s localhost:9000 | grep author
```

It should return `<meta name="author" content="Portainer.io" />` if working correctly.

**Comment by siddjellali** [comment]
ooooh yeah ! It works. I guess is related to brigde network issue.
I have your link here. https://github.com/markdumay/synology-docker/issues/12

Appreciate your support !

**Comment by markdumay** [comment]
In this case, it might be easier to run the container using a host network. Try the following:
```
docker run -d --name=portainer --network host --restart=always -v /var/run/docker.sock:/var/run/docker.sock portainer/portainer-ce
```

You should be able to reach portainer from the browser at `http://YOUR_NAS_IP:9000` from any machine on your local network.

**Comment by siddjellali** [comment]
You make my day :P

**Comment by siddjellali** [comment]
For your information, i reproduce the issue.
I add a rule in iptable 
`iptables -P FORWARD ACCEPT `
and it works now !

**Comment by markdumay** [comment]
Sounds promising! Are you now able to access containers attached to a bridge network remotely?

**Comment by markdumay** [comment]
I found similar advise on this forum [post](https://community.synology.com/enu/forum/1/post/131600). I'll update issue #12 and start working on a fix.
