### ISSUE TITLE
Lost of connectivity after reboot

### ISSUE THREAD

**Issue by siddjellali** [markdumay/synology-docker#47]
Hi @markdumay, 

Each time i performed a reboot, i lost everything.
Docker is running but no of my container is available. I not sure what is the issue.
I solved this by restoring and upgrading all with your script.

Do you experience the same issue with reboot of your synology nas ?

**Comment by markdumay** [comment]
Hi @siddjellali, that's odd - it's not something that I recognize on my own NAS. I updated DSM to the latest available version (Version: 6.2.3-25426 Update 3) this morning, and Docker restarted all of my containers as expected. However, I'm still on Docker version 19.03.13 and haven't updated to the latest version yet. 

How did you initially start your containers? Do you use Synology's Docker UI, Portainer, Docker Compose, or another method? Does the log file `/var/log/Docker/docker.log` provide any clues (NB: you can switch to root with `sudo -I` from the command line)?

**Comment by jprates** [comment]
A bit off-topic, but what NAS do you own @markdumay ?
My DS916+ has the same DSM version as yours and yet the latest docker version available to me is the old 18.09.0-0513.

**Comment by markdumay** [comment]
My NAS is a Synology DS918+ with 8GB RAM. This [repository](https://github.com/markdumay/synology-docker) hosts a script to manually update the Docker Engine and/or Docker Compose to the latest version available (as maintained by the Docker team instead of by Synology). I developed the script to address the lack of decent Docker Swarm support by Synology's Docker package. However, the script is not supported by Synology and it does have to some drawbacks (see [known issues](https://github.com/markdumay/synology-docker/issues/42)).

**Comment by jprates** [comment]
Ah, ok, that explains it.
Thanks, I already knew that repository but alas my NAS is working on btrfs, so it does not work for me.
Probably the reason Synology themselves are taking more time to release v19, they usually are only one release behind.

**Comment by siddjellali** [comment]
Hi @markdumay sorry for my late reply. _Very good Christmas and New Year :P_ 
Well i have also did (automaticaly) the upgrade of my NAS in 6.2.3-25426 Update 3 during the night;
In the next morning, i noticed all my container was up but not reachable even after restart the all nas twice ^^.

When my nas reboot i have to restore with my backup and upgrade the nas again.
Maybe a specific command on your script help to refresh/reload a specific element...

Did you the upgrade to docker version 20.10.1 ?

```
$ docker version
Client: Docker Engine - Community
 Version:           19.03.14
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        5eb3275
 Built:             Tue Dec  1 19:14:24 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.14
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       5eb3275
  Built:            Tue Dec  1 19:21:08 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.9
  GitCommit:        ea765aba0d05254012b0b9e595e995c09186427f
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

```
$ docker-compose version
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Comment by markdumay** [comment]
No worries - hope you had a wonderful Christmas, despite Covid-19! I just finished watching "Death to 2020" on Netflix - spot on I'd say.

I'm still on the old Docker version `19.03.13` and haven't updated to the latest version yet. My docker-compose is on version `1.27.4` though. Did you have to revert back to the previous Docker version to get it up and running? And what kind of additional command / specific element to reload would you be looking for?

**Comment by siddjellali** [comment]
Hehe thanks. I hope all is well on your side too.
Did you have to revert back to the previous Docker version to get it up and running? **YES** 
And what kind of additional command / specific element to reload would you be looking for? **it's what I am looking for.**

Any idea ?

**Comment by siddjellali** [comment]
Hi, for information, after a stop and start; all services go up again.
No need to reinstall anymore;

```
synoservicectl --stop pkgctl-Docker
synoservicectl --start pkgctl-Docker
```

**Comment by siddjellali** [comment]
Hi @markdumay for information, the last update of yesterday solved my issue;
```
DSM 6.2.4-25556
Docker version 18.09.8, build bfed4f5
docker-compose version 1.24.0, build 0aa59064
```

**Comment by markdumay** [comment]
ok, glad to hear the issue has been solved for you!
