### ISSUE TITLE
New package release on synology website

### ISSUE THREAD

**Issue by mqtt-fan** [markdumay/synology-docker#52]
There is a new Docker Engine (20.10.03) released on https://www.synology.com/de-de/dsm/packages/Docker

Maybe this content can help to understand how to build newer versions

**Comment by markdumay** [comment]
Thanks for the update @mqtt-fan. I checked the release notes, there is still no mentioning about proper Docker Swarm support unfortunately. 

My impression is that Synology modifies the Docker source code and recompiles the binaries themselves. When you extract the `Docker-x64-20.10.3-0552.spk` file manually (using `tar xf`), you can view a bunch of files, of which the script files are the most interesting. The binaries are embedded in the `package.tgz` file, within the folder `/usr/bin`. However, I haven't found the source code of those binaries though.

I'm closing this issue for now, but I do welcome suggestions from anyone.
