### ISSUE TITLE
[FeatureRequest] Add nvidia-docker2 support

### ISSUE THREAD

**Issue by wills106** [markdumay/synology-docker#55]
I was wondering now that the built in Synology Docker is Version 20.10.x would it be possible to use a similar method you are using to only add in the NVIDIA Container Toolkit "nvidia-docker2" so that GPU's can be used in the Synology Docker environment?

https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html

This would allow for Machine Learning and Transcoding support on Docker images that support it.

**Comment by markdumay** [comment]
Interesting question! It looks like your Synology NAS would require a NVIDIA GPU to make this work? If so, this [link](https://www.synology.com/en-global/dsm/packages/NVIDIARuntimeLibrary) seems to suggest only the models DVA3221 and DVA3219 have a NVIDIA GPU.

Synology uses a heavily modified Linux distribution with a package manager called `ipkg`, so the steps listed in your link would not apply directly. Perhaps Synology's package `NVIDIA Runtime Library` would be sufficient. My personal NAS is not compatible it seems, so it would be difficult for me to develop and test such a script I'm afraid.

**Comment by wills106** [comment]
Yes you would need an Nvidia GPU in there. Getting a GPU working isn't too hard from a driver point of view.

I am using a "DS918" I downloaded the pat file for DS1618 matching the same revision as mine ie  6.2.3-25426-3

Extracted:
nvidia-modeset.ko
nvidia-uvm.ko
nvidia.ko

Copied them into a folder in Volume1
Logged in via ssh and then did sudo -i
Copied them from the folder in Volume1 to /usr/lib/modules/
Insmod the 3 nvidia files.

Downloaded the runtime file and removed all reference to DVA and versions, so on installation it doesn't check it's a DVA machine.

Manually Installed the runtime library.

Then nvidia-smi works.

As to Physically getting the GPU in there might be a different problem.

I'm just not sure if nvidia-docker2 is a complete Docker replacement or a helper wrapper for it?
If it's a complete replacement we'll probably run into the same issue where the Synology Docker GUI breaks.

**Comment by markdumay** [comment]
Looks like you did quite some research already! So if I understand correctly, the following command now works for you?
```
sudo docker run --rm --gpus all nvidia/cuda:11.0-base nvidia-smi
```

Maybe it's my lack of understanding, but what is the advantage of getting `nvidia-smi` up and running without a physical GPU?

**Comment by wills106** [comment]
Sorry for the confusion, I have a GTX1650 in my Synology. nvidia-smi shows that it's working, once you have installed the drivers.

When I do the above command I get:

docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].

nvidia-docker2 adds the GPU parts either as a wrapper to the normal docker or replaces it? That's the bit I'm not sure how it works yet.

**Comment by markdumay** [comment]
Ah, thanks for clarifying. It’s difficult to say what’s causing this. Two things come to mind:
- You might need to modify the `daemon.json` file to include the GPU configuration 
- You might need to manually restart the docker daemon

Sorry I can’t be of more help.

**Comment by markdumay** [comment]
@wills106, any news regarding your investigation? I suggest to close this issue for now, unless you want to keep on working on it.

**Comment by wills106** [comment]
I'll close it for now.
