### ISSUE TITLE
Updating to DSM 7

### ISSUE THREAD

**Issue by hirenshah** [markdumay/synology-docker#56]
Does anyone know what happens to Docker and macvlan network configurations when the Synology NAS is updated to DSM 7?

I'm guessing that everything will need to be updated again and the network reconfigured, but just thought I would ask so I can be prepared :)

**Comment by markdumay** [comment]
Hi @hirenshah, I updated to DSM 7 without any issues. I've adjusted the Docker script to support DSM 7 (see release v1.4.0). I'm running my macvlan network without any issues. I updated to DSM 7 first, and then ran the script in this repository. It wouldn't hurt to make a backup of your files though ;-).

**Comment by hirenshah** [comment]
@markdumay Did you have to set up your macvlan network again after upgrading to DSM 7?  I've not touched my set up since we last spoke (when you first created this script) so I don't actually remember everything I did to get it working lol.

**Comment by markdumay** [comment]
I had to set up my macvlan network again indeed. I used this [script](https://github.com/markdumay/synology-pihole), which might be helpful.

**Comment by hirenshah** [comment]
> I had to set up my macvlan network again indeed. I used this [script](https://github.com/markdumay/synology-pihole), which might be helpful.

I didn't have to set mine up again. I have this script which I run on boot to set the routing:

```
#!/bin/sh
PATH=/usr/local/bin:/usr/bin:/bin
while ! ip link show bond0 | grep -q 'state UP'; do
    sleep 1
done

ip link add macvlan_link link bond0 type macvlan  mode bridge
ip addr add 192.168.1.240/32 dev macvlan_link
ip link set macvlan_link up
ip route add 192.168.1.240/28 dev macvlan_link
iptables -P FORWARD ACCEPT
```

**Comment by markdumay** [comment]
Ok, great it worked out for you! Were you able to upgrade to DSM 7 without any other issues?

**Comment by hirenshah** [comment]
No issues as far as I can tell... so far anyway lol.

**Comment by markdumay** [comment]
You should be fine then! I upgraded to DSM 7 two months ago and haven't encountered any issues with the Docker update script and the macvlan network myself. Ok to close this issue for now?
