### ISSUE TITLE
[BUG] Docker-compose download error

### ISSUE THREAD

**Issue by 77weiss** [markdumay/synology-docker#57]
**Describe the bug**
with the script docker-compose cannot be downloaded because since docker-compose v2 the version part of the download url contains a leading 'v' which the script doesn't reflect.

The correct URL has to be

https://github.com/docker/compose/releases/download/v2.1.1/docker-compose-Linux-x86_64
not (https://github.com/docker/compose/releases/download/2.1.1/docker-compose-Linux-x86_64

**To reproduce**
./syno_docker_update.sh update

**Expected behavior**
Download should work

**Log file**
 sudo ./syno_docker_update.sh update
Update Docker Engine and Docker Compose on Synology to target version

Current DSM version: 7.0.1
Current Docker version: 20.10.3
Current Docker Compose version: 1.28.5
Target Docker version: 20.10.11
Target Docker Compose version: 2.1.1

WARNING! This will replace:
  - Docker Engine
  - Docker Compose
  - Docker daemon log driver

Are you sure you want to continue? [y/N] y
Step 1 from 10: Downloading target Docker binary (https://download.docker.com/linux/static/stable/x86_64/docker-20.10.11.tgz)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 60.4M  100 60.4M    0     0  4426k      0  0:00:13  0:00:13 --:--:-- 5157k
Step 2 from 10: Downloading target Docker Compose binary https://github.com/docker/compose/releases/download/2.1.1/docker-compose-Linux-x86_64
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9  100     9    0     0     17      0 --:--:-- --:--:-- --:--:--    17
**ERROR: Binary could not be downloaded**

**Docker daemon configuration**
Capture the content of the file `/var/packages/Docker/etc/dockerd.json`.

**Additional context**

**Comment by rsik** [comment]
https://github.com/markdumay/synology-docker/blob/743dcc4a755178f7f32e9036ca4beecd9f74d41e/syno_docker_update.sh#L755

`https://github.com/docker/compose/releases/download/2.1.1/docker-compose-Linux-x86_64` generated from script
`https://github.com/docker/compose/releases/download/v2.1.1/docker-compose-linux-x86_64` actual link ('v' was missing and 'L' was capitalized')

Pesky missing and capital letters :wink:

**Comment by markdumay** [comment]
Thanks for submitting the issue! I have updated the script and tested compatibility with the latest DSM package. It should now determine the correct download path for all major releases of Docker Compose. A new release of `synology-docker` is available as `v1.4.1`.

**Comment by markdumay** [comment]
In addition, I published a new release `v1.4.2`. This should fix the version detection of the installed Docker Compose binary. It seems the output of `docker-compose -v` has been updated too.
